### ISSUE TITLE
Chercher comment faire et réaliser les graphes et diagrammes en JS

### ISSUE THREAD

**Issue by GithRomain** [GithRomain/MasterCamp#28]

**Comment by FrancoisCharvet** [comment]
### API Chart.js

- permet d'intégrer **_tous types de graphes_** assez simplement en incluant les **_données de notre choix_**
- permet également de **_créer des animations_**
- disponible sur **_Github_**: https://github.com/chartjs/Chart.js
- et **_npm_**: https://www.npmjs.com/package/chart.js (nmp i chart.js)
- doc détaillée **_pas à pas_**, et sur des **_points spécifiques_**: https://www.chartjs.org/docs/latest/getting-started/

- également une **_vidéo_** si vous êtes allergiques aux docs: https://youtu.be/2_VRcWKv-8Y
