### ISSUE TITLE
Diagramme UML (UCD pour nous)

### ISSUE THREAD

**Issue by GithRomain** [GithRomain/MasterCamp#7]
Faire un UCD bien complet pour alimenter la doc

**Comment by mustache956** [comment]
![StatechartDiagram1](https://user-images.githubusercontent.com/73854536/174270864-42928752-aa24-453a-bd1f-ea90b9f5b818.png)
![UseCaseDiagram1](https://user-images.githubusercontent.com/73854536/174270872-8ff77197-bf3e-44ba-870c-8484fab216b8.png)

**Comment by mustache956** [comment]
[UML_Diagrams.zip](https://github.com/GithRomain/MasterCamp/files/8926409/UML_Diagrams.zip)
